# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd167bbcb52c5f167a9591eec78606bcd03cfa280fbb30354b95e45a445cb89f437d45d7fe7d0cb5ae0cca17c16cce129e02220754ea488b0c794782b0c63275
  paybook: 115524a855da6cb8c36aaed6567ee65f
test:
  secret_key_base: 15bfff30238294957b1b1e3c9b358ffb033ad43aa34697774376187e3c59f0bfb40ee6dbee762d84932555f7072766915169c13191c9095640135f2315b10632
  paybook: 115524a855da6cb8c36aaed6567ee65f
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paybook: 115524a855da6cb8c36aaed6567ee65f
